### ISSUE TITLE
Todo App 요구사항

### ISSUE THREAD

**Issue by KimByoungMoo** [KimByoungMoo/Github-exam#1]
### 필요한 기능
- Todo 생성

### 기본 구성
1. [ ] Todo List 등록
2. [ ] Todo List 수정
3. [ ] Todo List 조회
4. [ ] Todo List 삭제

### 추가 구성
1. [ ] 완료 된 할일 체크기능
2. [ ] 할 일 일괄등록

### 예상 작업 시간
- 3h
